JB 15-16
friends-library/john-barclay pull request #33
Opened 2021-02-04 16:38 UTC by maijapapaya

@jaredh159 @Henderjay

2021-02-04 16:59 UTC, maijapapaya commented on diary-alexander-jaffray/modernized/32-ch-16-scotland.adoc
> +[.embedded-content-document.epistle]
Ok so this first paragraph here is embdded in the ODT and looks like it should be in the PDF as well, but doesn't seem to really be part of the epistle. I wonder if it was just a quote from the "Friends of Aberdeen" that didn't get ended before they inserted the epistle? Or is it taken from some other writing as part of the epistle? I just can't tell from any of the context either. I tried to attach a picture, but it didn't seem to work. It's on page 359 in the PDF and page 243 of the ODT.

2021-02-04 17:01 UTC, maijapapaya commented on diary-alexander-jaffray/modernized/32-ch-16-scotland.adoc
> +[.postscript]
Also here I guess isn't part of the epistle either. Maybe I missed why these were included in his actual epistle.

2021-02-04 17:06 UTC, maijapapaya commented on diary-alexander-jaffray/modernized/32-ch-16-scotland.adoc
> +[.embedded-content-document.letter]
So here begins a letter that has letters within. I did what I thought looked good, but idk if it's right! It seems that John Bowstead wrote a letter to Francis Stamper about Peter Gardiner, and inserted a couple of Peter's letters. At least that's what I could make of it. :)

2021-02-04 19:49 UTC, Henderjay requested changes
I saw your notes on chapter 16. It was a tricky chapter because there was a letter that appeared within a note from a meeting. And then later on (like you thought) there were a few letters from Peter Gardiner stuck inside a letter from John Bowstead. We don't really have a convention for how to deal with letters within letters, but I think what you did looks as good as anything I could think of.  👍🏻. The only thing I'm going to have you change is actually in chapter 15, where I left the note. That chunk should probably be a block quote. (I only marked it in the original, but it will need to be a block quote in both modernized and original).

2021-02-04 19:49 UTC, Henderjay commented on diary-alexander-jaffray/modernized/31-ch-15-scotland.adoc
>  He was distinguished by strong mental powers, particularly by great penetration,
So, from here to the end of the chapter is a quote from the book A Short Account of the Life and Writings of Robert Barclay, by John G. Bevan. So, I think these three paragraphs should be a block quote. 👍🏻

2021-02-10 15:50 UTC, merged

2021-02-10 15:50 UTC, Henderjay commented
great, merged!