Concluding and Notes
friends-library/john-barclay pull request #37
Opened 2021-02-09 14:55 UTC by maijapapaya

@jaredh159 @Henderjay

2021-02-09 16:29 UTC, maijapapaya commented
This is only notes A-G with the italicization added back in....Jared wanted me to do smaller chunks to make sure my italicizing doesn't disappear again. So I'm doing like 7 notes at a time. Seems to be working okay so far!

2021-02-09 20:35 UTC, Henderjay requested changes
Hey Maija, just a couple things to change on this one. The Concluding Observations needs the chapter synopsis on the original version. And I thought that Note P. (in both the original and modernized) needs a blurb heading. 👍🏻

2021-02-09 20:35 UTC, Henderjay commented on diary-alexander-jaffray/modernized/37-concluding-observations.adoc
> +* On the state of the church at large, with reference to the successive stages of her reformation, and occasioned by a view of that share and interest, which the Society of Friends have ever taken th
This chapter-synopsis looks good. But looks like you forgot to do it on the original too. :)

2021-02-09 20:35 UTC, Henderjay commented on diary-alexander-jaffray/modernized/38-notes-memoirs.adoc
>  A Seasonable Warning and serious exhortation to,
This little chunk, starting with "A Seasonable Warning..." etc I think would look better as a blurb heading, or something like that. Both here and in the original. 👍🏻

2021-02-10 19:37 UTC, merged

2021-02-10 19:37 UTC, Henderjay commented
Ok, this all looked good. Merged!